version: '2'

services:

  web:
      build: ./nginx
      ports:
          - "8085:80"
      volumes:
          - ../app:/code
          - ./site.conf:/etc/nginx/conf.d/site.conf
      links:
          - php
  php:
      image: php:7-fpm
      volumes:
          - ../app:/code
